dead code elimination optimization
mit-plv/bedrock2 pull request #393
Opened 2023-11-25 00:53 UTC by 0adb

Version of dead code elimination optimization that currently compiles and is integrated into main Pipeline.v .

2023-11-27 22:43 UTC, samuelgruetter requested changes
Looks great :tada: 

Many of the lemmas you proved seem generally useful and would be good to have in coqutil (see also by-comment about that), and then some whitespace/empty-lines cleanup, and we're good :smile:

2023-11-27 22:43 UTC, samuelgruetter commented on compiler/src/compiler/DeadCodeElimHelper.v
> +End WithArguments0.
Thanks for all the work on proving lemmas about lists, sets, and maps :+1: 
To make sure the next person who needs such lemmas finds them and doesn't reprove all of them, it would be good to move them to coqutil:
* map-related lemmas to `coqutil.Map.MapEauto`
* PropSet-related lemmas to `coqutil.Datatypes.PropSet`
* purely list-related lemmas to `coqutil.Datatypes.List`
And as you're doing the move, it would also be good to generalize `eqb`, which currently refers to `String.eqb`, by making it a context variable with an `EqDecider eqb`.

2024-01-11 20:57 UTC, 0adb commented
Latest comment should have formatting changes requested for DeadCodeElim.v and DeadCodeElimDef.v. Helper lemmas have been moved / modified in the PR for coqutil (https://github.com/mit-plv/coqutil/pull/110). Probably won't work on possible SStackalloc optimization / will leave comment for future, focusing on thesis first. After coqutil PR is merged and bedrock2's version of coqutil is updated, would be good to update this optimization to use the lemmas via coqutil and delete DeadCodeElimHelper.v

2024-03-10 21:22 UTC, 0adb commented
Most recent commit should have bumped optimization to most recent commits / coqutil version. Pending GitHub workflow to verify, but compiles successfully locally.

2024-03-11 15:22 UTC, merged

2024-03-11 15:24 UTC, samuelgruetter commented
Great, thanks for finishing this all the way :+1: 
Happy to have DCE now :tada: :partying_face:

2024-07-21 05:30 UTC, OwenConoly commented on compiler/src/compiler/DeadCodeElimDef.v
> +          (dce body u) *)
Perhaps I'm a bit late here, but I recently happened to look at this file, and I have some thoughts about it.

Interestingly, I think this optimization is not sound!  (Unless we add some extra hypotheses.)  Consider the following counterexample, where the map is full.  Say a word is four bytes.  Let `s = stackalloc 4 as x; skip`*.  Let `m = fun _ => Some 0`\*.  Let `l` and `t` be arbitary.  We have `exec s t m l (fun _ _ _ => False)`, since the `map.split mCombined mSmall mStack` hypothesis, in the definition of `exec`, is always false.  On the other hand, after applying the optimization, we get the new statement `s' = skip`.  And clearly it is not the case that `exec s' t m l (fun _ _ _ => False)`.

That counterexample suggests defining some function `stack_space_needed : stmt -> nat`, and then giving the DCE phase correctness theorem a hypothesis of the form
`exists a mStack, Memory.anybytes (stack_space_needed s) a mStack /\ map.split m mStack`.

Amusingly, this hypothesis does not suffice.  Here's a counterexample.  Take `s = stackalloc 4 as x; load 0`.  Let `m = fun addr => if addr < 4 then None else Some 0`.  With `l` and `t` arbitrary as before, we have `exec s t m l (fun _ _ _ => True)`.  However, after applying the optimization, we get the statement `s' = load 0`.  And clearly it's not the case that `exec s' t m l (fun _ _ _ => True)`.

I believe a hypothesis that actually suffices is 
`exists a mStack, Memory.anybytes (2 * stack_space_needed s) a mStack /\ map.split m mStack`.

^Certainly that hypothesis could be weakened by doing clever things: for instance, there's no need for all the memory to be contiguous.

This new hypothesis obviously fixes the counterexample.  Further, I think writing a proof using this hypothesis would be doable---the idea would be that, every time there is a load or a store at a location that is _independent of the value in the local variable x_ (as in `stackalloc 4 as x`), then we can just choose to instantiate the `forall a mStack` of the stackalloc-exec judgment with some values such that the load/store location is not in `mStack`.  The point is that the hypothesis says we have two disjoint choices for how to instantiate `mStack`, and at most one of the choices can contain the load/store location.

*My mental model of Bedrock2 memory is that it's a map `word -> option byte`, so I'm just writing things like that here, for simplicity.

2024-07-21 05:36 UTC, OwenConoly commented on compiler/src/compiler/DeadCodeElimDef.v
> +          (dce body u) *)
Also: if we end up merging the version of the constant-timeness stuff that puts the stack-allocation oracle into the definition of `exec`, I'm not sure how that would interact with proving this optimization correct.  Certainly the soundness of the optimization would be unchanged, but maybe it gets slightly harder to prove?

2024-07-21 05:58 UTC, OwenConoly commented on compiler/src/compiler/DeadCodeElimDef.v
> +          (dce body u) *)
Actually, maybe it gets dramatically harder to prove if we put the oracle into `exec`... it seems like we'd need to carry around multiple `exec` hypotheses, each corresponding to a different oracle, through the DCE phase proof.  Then when we get to a stackalloc case, we say 'one of these oracles gives us what we want'.  The issue would be that we can't really do induction on a large (infinite?) number of different `exec` hypotheses all at once.  And even if we somehow get around that, it seems like an extra complication to have to know 'ahead of time' (i.e., before we start doing induction on the `exec` judgment) how to instantiate the several different oracles...

2024-07-21 17:12 UTC, andres-erbsen commented on compiler/src/compiler/DeadCodeElimDef.v
> +          (dce body u) *)
Interesting. The null-dereference issue and double-allocation workaround remind me of [twinsem](https://research.ralfj.de/twinsem/twinsem.pdf).

Note that the current semantics (without leakage) is already odd: stack overflow should never happen, and we prove it never happens elsewhere, which is why this definition gets away with assigning stack overflow *vacuous behavior* rather than undefined behavior as it intuitively would have.

2024-07-22 17:50 UTC, OwenConoly commented on compiler/src/compiler/DeadCodeElimDef.v
> +          (dce body u) *)
Interesting!  Looks like they had basically the same goal, of preventing "unobserved blocks from being accessed via guessed addresses", and they solved it basically using the same idea.  So it's nice to know that the double-allocation thing works out nicely.

Nonetheless, it really does seem like a workaround, rather than something that should have to be done.  Compilers should be able to remove useless stackallocs (and do other more-complicated manipulations, like those in the twinsem paper) without having to require, as a precondition to the compiler theorem, that we have twice the available stack space that we actually need.

With the twinsem paper, they have no option but to do the double-allocation thing, since they can't change what C looks like.  It seems to be a clever yet awkward workaround of the fact that, just from looking at a load/store operation in a C program, you can't immediately tell which block of memory the programmer is trying to access.  Ideally, it seems programmers should have to say which block they're trying to access, via some annotations that just disappear after compilation.  (Perhaps this sounds uncomfortably like the sort of feature that belongs to a higher-level language than C.)

With Bedrock2 the semantics could be defined so that a load or store fails unless it is annotated with the correct block label, and then the compiler could easily make these optimizations, without requiring the extra "there is more stack space than we actually need" hypothesis.  (Due to the vacuous behaviour of stack overflow, thee optimizations would still require a "there is enough stack space" hypothesis, but we need to have that eventually anyway.)

Sadly, this would probably be horribly complicated: the state would have to keep track of which memory belongs to which block.  Worse, the annotations would probably have to be passed as arguments to functions, if the functions want to interact with memory allocated outside of the function body.  Of course, the annotation arguments would not be "real" function arguments: just some annotations that appear in source code but not in the assembly code output by the compiler.

2024-07-22 19:32 UTC, OwenConoly commented on compiler/src/compiler/DeadCodeElimDef.v
> +          (dce body u) *)
The only problem with the current memory semantics is that it allows program proofs to rely on the finite size of the address space.  If we prevent this somehow, then we can write twinsem-style compiler proofs without actually requiring the extra stack space (or even any stack space at all, since this would deal with the vacuous behaviour issue as well).

It feels like it should be easy to write semantics where we have an infinite address space, but it is hard because words have finite width.  One approach would be to say that to prove a program correct, you have to prove that it's correct for all sufficiently large word sizes - much like how, with the leakage-trace-augmented semantics, we said that to prove a program correct, you have to prove that it's correct for all possible values of `pick_sp`.  This would require some notion of, e.g., 32-bit words being a subset of 64-bit words, and 32-bit address spaces being included in 64-bit address spaces and so on.  Which would be a complication.

2024-08-22 21:25 UTC, OwenConoly commented on compiler/src/compiler/DeadCodeElimDef.v
> +          (dce body u) *)
@andres-erbsen your email reminded me that this discussion exists; upon thinking about it again, I am finding that my last suggestion, of proving source programs for every sufficiently large bitwidth, is sounding less silly than I thought at first.

Here's a sketch of how it could go:
- Instead of `m : word -> option byte`, we have `m : nat -> option byte`.
- Syntax of load/store operations is unchanged: they take words as input, give bytes as output.
- Semantics of load/store operations is almost unchanged, except that we use `word.unsigned` to get the address
- Source-program correctness is no longer defined as a judgment like `exec ...`.  Rather, it is `forall width' >= width0, exec width' ...`.  The compiler pass doing the dead-stackalloc-removal thing would _not_ preserve `exec ...` postconditions, but it would preserve `forall width' >= width0, exec width' ... ` postconditions (even when the postcondition depends on `width'`).

In principle, the only problem with this is that, if you write a program that succeeds on a 32-bit computer but crashes on a 64-bit computer, then you can't prove it correct (in this new sense of 'proving it correct').  I can't think of any use cases for that, but maybe they exist?  If they don't, then to me this seems like a nicer semantics than either a twinsem-ish solution (although I guess that's basically what it is, in disguise), or a provenance-ish solution.

In practice, there are probably more issues here, but I don't know what they are.

2024-08-23 02:04 UTC, OwenConoly commented on compiler/src/compiler/DeadCodeElimDef.v
> +          (dce body u) *)
Oops, that is not even almost right.  For one thing, it breaks any program that uses unsigned integer overflow (or maybe it's not called overflow - wrapping, or whatever).  Never mind.